dependencies:
  - conda-forge::numpy
  - conda-forge::pip
  - conda-forge::python=3.11
  - conda-forge::pandas
  - conda-forge::astropy
  - conda-forge::scipy
  - conda-forge::tqdm
  - pip:
      - matplotlib
      - graphviz
      - emcee
      - corner
      - specutils